import { Roboto_Mono } from "next/font/google";
import "./globals.css";

import { Header } from "./components/Header";

const robm = Roboto_Mono({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "dududu, dadadad",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={robm.className}>
        <Header />
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
